export const GAMECOACH_GG_URLS: Record<string, string> = {
  Aquarius: "https://gamecoach.gg/esports/haloinfinite/aquarius",
  Argyle: "https://gamecoach.gg/esports/haloinfinite/argyle",
  Empyrean: "https://gamecoach.gg/esports/haloinfinite/empyrean",
  Forbidden: "https://gamecoach.gg/esports/haloinfinite/forbidden",
  Fortress: "https://gamecoach.gg/esports/haloinfinite/fortress",
  Fuel: "https://gamecoach.gg/esports/haloinfinite/fuel",
  Inquisitor: "https://gamecoach.gg/esports/haloinfinite/inquisitor",
  Interference: "https://gamecoach.gg/esports/haloinfinite/interference",
  Lattice: "https://gamecoach.gg/esports/haloinfinite/lattice",
  "Live Fire": "https://gamecoach.gg/esports/haloinfinite/livefire",
  Origin: "https://gamecoach.gg/esports/haloinfinite/origin",
  Recharge: "https://gamecoach.gg/esports/haloinfinite/recharge",
  Solitude: "https://gamecoach.gg/esports/haloinfinite/solitude",
  Streets: "https://gamecoach.gg/esports/haloinfinite/streets",
};
