export enum InteractionButton {
  Retry = "btn_stats_retry",
  LoadGames = "btn_stats_load_games",
  FixPlayerSelect = "btn_stats_fix_player_select",
  FixGamesSelect = "btn_stats_fix_games_select",
  FixOutcomeSelect = "btn_stats_fix_outcome_select",
  FixConfirm = "btn_stats_fix_confirm",
  FixCancel = "btn_stats_fix_cancel",
  ManualQueueSelect = "btn_stats_manual_queue_select",
  ManualQueuePreviousPage = "btn_stats_manual_queue_previous_page",
  ManualQueueNextPage = "btn_stats_manual_queue_next_page",
  ManualPlayerSelect = "btn_stats_manual_player_select",
  ManualGamesSelect = "btn_stats_manual_games_select",
  ManualOutcomeSelect = "btn_stats_manual_outcome_select",
  ManualConfirm = "btn_stats_manual_confirm",
  ManualSetQueueNumber = "btn_stats_manual_set_queue_number",
  ManualQueueNumberModal = "btn_stats_manual_queue_number_modal",
  ManualAdjustScore = "btn_stats_manual_adjust_score",
  ManualScoreModal = "btn_stats_manual_score_modal",
}
