// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	SERVICE_API_TOKENS_DEV: KVNamespace;
	SERVICE_API_TOKENS_STAGING: KVNamespace;
	SERVICE_API_TOKENS_PRODUCTION: KVNamespace;
	DISCORD_APP_ID: string;
	DISCORD_TOKEN: string;
	DISCORD_PUBLIC_KEY: string;
	XBOX_USERNAME: string;
	XBOX_PASSWORD: string;
	KV_NAMESPACE: string;
}
