// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	DISCORD_APP_ID: string;
	DISCORD_TOKEN: string;
	DISCORD_PUBLIC_KEY: string;
	XBOX_USERNAME: string;
	XBOX_PASSWORD: string;
	SOMETHING: string;
}
