name = "guilty-spark"
main = "./src/server.mts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
upload_source_maps = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[kv_namespaces]]
binding = "SERVICE_API_TOKENS"
id = "94d9b7f70ef940cc86070091eb22eda9"
preview_id = "4b92f4658bba43699b7620a64281b2a1"

[env.staging]
name = "guilty-spark-staging"

[env.production]
name = "guilty-spark"
