name = "guilty-spark"
main = "./src/server.mts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
upload_source_maps = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[env.dev]
name = "guilty-spark-dev"
workers_dev = true

[env.staging]
name = "guilty-spark-staging"
workers_dev = true

[env.production]
name = "guilty-spark"
workers_dev = false
