name = "guilty-spark"
main = "./src/server.mts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
upload_source_maps = true
kv_namespaces = [
  { binding = "APP_CONFIG", id = "374fa9b9bed741fe9b5cb2d777206413" }
]
d1_databases = [
  { binding = "DB", database_name = "staging-db-guilty-spark", database_id = "f36b6b07-dc66-43d8-8653-571b473c6cd5" }
]


[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.


[env.staging]
name = "guilty-spark-staging"
kv_namespaces = [
  { binding = "APP_CONFIG", id = "15f902ee57834484a4809a839a5c0a71" }
]
d1_databases = [
  { binding = "DB", database_name = "staging-db-guilty-spark", database_id = "f36b6b07-dc66-43d8-8653-571b473c6cd5" }
]


[env.production]
name = "guilty-spark"
kv_namespaces = [
  { binding = "APP_CONFIG", id = "2b593da40c7e4762be0c2095afdad49f" }
]
d1_databases = [
  { binding = "DB", database_name = "prod-db-guilty-spark", database_id = "fa6747b9-e9e0-47ca-891b-d4608ade66a3" }
]
