name = "guilty-spark"
main = "./src/server.mts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
upload_source_maps = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[kv_namespaces]]
binding = "SERVICE_API_TOKENS"
id = "eae67afcb62847beb5502014962ac15b"

[env.dev]
name = "guilty-spark-dev"

[env.staging]
name = "guilty-spark-staging"

[env.production]
name = "guilty-spark"
