name = "guilty-spark"
main = "./src/server.mts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
upload_source_maps = true

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[env.staging]
name = "guilty-spark-staging"
[[kv_namespaces]]
binding = "SERVICE_API_TOKENS"
id = "ced62798d67d44e89104646327a0b44c"

[env.production]
name = "guilty-spark"
[[kv_namespaces]]
binding = "SERVICE_API_TOKENS"
id = "7332bc767e3e43738ec3bdbd6d22db15"
