import type { APIMessage } from "discord-api-types/v10";
import { ComponentType } from "discord-api-types/v10";
import { Preconditions } from "@guilty-spark/shared/base/preconditions";
import { z } from "zod";
import type { MapMode } from "../../services/halo/hcs";
import { ALL_MODES, MAP_COUNTS } from "../../services/halo/hcs";
import { MapsFormatType, MapsPlaylistType } from "../../services/database/types/guild_config";
import { InteractionComponent, mapFormatLabels, mapPlaylistLabels } from "../../embeds/maps-embed";
import { GAMECOACH_GG_URLS } from "./gamecoachgg";

export interface MapsDraft {
  userId: string;
  locked: boolean;
  attributionLabel?: "Generated by" | "Cleared by" | undefined;
  plan?: { queueNumber: number; token: string } | undefined;
  autoQueueNumber?: number | undefined;
  count: number;
  playlist: MapsPlaylistType;
  format: MapsFormatType;
  maps: { mode: MapMode; map: string }[];
}

export function normalizeMapsFormat(format: MapsFormatType, availableModes: MapMode[]): MapsFormatType {
  return availableModes.length > 1 ? format : MapsFormatType.SLAYER;
}

function findSelectedValue(message: APIMessage, customId: string): string | undefined {
  for (const row of message.components ?? []) {
    if (row.type !== ComponentType.ActionRow) {
      continue;
    }

    for (const component of row.components) {
      if (component.type !== ComponentType.StringSelect || component.custom_id !== customId) {
        continue;
      }

      return component.options.find((option) => option.default === true)?.value;
    }
  }

  return undefined;
}

function readSelectedValue(message: APIMessage, customId: string): string {
  return Preconditions.checkExists(findSelectedValue(message, customId), `No selected value for ${customId}`);
}

function isMapsMessageLocked(message: APIMessage): boolean {
  return findSelectedValue(message, InteractionComponent.CountSelect) == null;
}

function readMapName(value: string): string {
  const link = /^\[[^\]]+\]\(([^)]+)\)$/.exec(value);
  if (link == null) {
    return value;
  }

  const url = Preconditions.checkExists(link[1]);
  return Preconditions.checkExists(
    Object.entries(GAMECOACH_GG_URLS).find(([, candidateUrl]) => candidateUrl === url)?.[0],
    `Unknown map link ${url}`,
  );
}

function readMapsFromEmbeds(message: APIMessage): { mode: MapMode; map: string }[] {
  const fields = message.embeds.flatMap((embed) => embed.fields ?? []);
  const numberFields = fields.filter((field) => field.name === "#");
  const modeFields = fields.filter((field) => field.name === "Mode");
  const mapFields = fields.filter((field) => field.name === "Map");

  if (numberFields.length === 0 && modeFields.length === 0 && mapFields.length === 0) {
    return [];
  }

  if (
    numberFields.length === 0 ||
    numberFields.length !== modeFields.length ||
    numberFields.length !== mapFields.length
  ) {
    throw new Error("Map table fields are incomplete");
  }

  const maps: { mode: MapMode; map: string }[] = [];
  for (let fieldIndex = 0; fieldIndex < numberFields.length; fieldIndex++) {
    const gameNumbers = Preconditions.checkExists(numberFields[fieldIndex]).value.split("\n");
    const modes = Preconditions.checkExists(modeFields[fieldIndex]).value.split("\n");
    const mapNames = Preconditions.checkExists(mapFields[fieldIndex]).value.split("\n");
    if (gameNumbers.length !== modes.length || gameNumbers.length !== mapNames.length) {
      throw new Error("Map table columns do not align");
    }

    for (let rowIndex = 0; rowIndex < gameNumbers.length; rowIndex++) {
      if (Number(gameNumbers[rowIndex]) !== maps.length + 1) {
        throw new Error("Map table game numbers are out of order");
      }
      const modeValue = Preconditions.checkExists(modes[rowIndex]);
      const mode = Preconditions.checkExists(ALL_MODES.find((candidate) => candidate === modeValue));
      maps.push({ mode, map: readMapName(Preconditions.checkExists(mapNames[rowIndex])) });
    }
  }

  return maps;
}

function readPlaylistFromEmbed(message: APIMessage): MapsPlaylistType {
  const title = Preconditions.checkExists(message.embeds.find((embed) => embed.title != null)?.title);
  const label = title.replace(/^Maps: /, "");
  return z
    .enum(MapsPlaylistType)
    .parse(Preconditions.checkExists(Object.entries(mapPlaylistLabels).find(([, value]) => value === label)?.[0]));
}

function readFormatFromEmbed(message: APIMessage): MapsFormatType {
  const fieldValue = Preconditions.checkExists(
    message.embeds.flatMap((embed) => embed.fields ?? []).find((field) => field.name === "")?.value,
  );
  const match = /\| Format: (.+)$/.exec(fieldValue);
  const label = Preconditions.checkExists(match?.[1], "Map format metadata is missing");
  return z
    .enum(MapsFormatType)
    .parse(Preconditions.checkExists(Object.entries(mapFormatLabels).find(([, value]) => value === label)?.[0]));
}

function readAttributionFromEmbed(message: APIMessage): Pick<MapsDraft, "userId" | "attributionLabel"> {
  const fieldValue = Preconditions.checkExists(
    message.embeds.flatMap((embed) => embed.fields ?? []).find((field) => field.name === "")?.value,
  );
  const match = /^-# (Generated by|Cleared by|Confirmed by) <@([^>]+)>(?: \| Format: .+)?$/.exec(fieldValue);
  const label = Preconditions.checkExists(match?.[1], "Map attribution metadata is missing");
  const userId = Preconditions.checkExists(match?.[2], "Map attribution user is missing");
  if (label === "Confirmed by") {
    return { userId };
  }
  if (label === "Generated by" || label === "Cleared by") {
    return { userId, attributionLabel: label };
  }
  throw new Error("Invalid map attribution label");
}

function readPlanFromEmbed(message: APIMessage): MapsDraft["plan"] {
  const footer = message.embeds[0]?.footer?.text;
  if (footer == null) {
    return undefined;
  }
  const match = /^Queue: ([1-9]\d*) \| Plan: ([\da-f-]+)(?: \| AUTO Queue: [1-9]\d*)?$/.exec(footer);
  if (match == null) {
    throw new Error("Invalid map plan metadata");
  }
  return {
    queueNumber: z.number().int().positive().parse(Number(match[1])),
    token: z.uuid().parse(match[2]),
  };
}

function readAutoQueueNumberFromEmbed(message: APIMessage): number | undefined {
  const footer = message.embeds[0]?.footer?.text;
  if (footer == null) {
    return undefined;
  }
  const match = /(?:^| \| )AUTO Queue: ([1-9]\d*)$/.exec(footer);
  return match == null ? undefined : z.number().int().positive().parse(Number(match[1]));
}

export function readMapsDraftFromMessage(message: APIMessage): MapsDraft {
  const locked = isMapsMessageLocked(message);
  const maps = readMapsFromEmbeds(message);
  const count = locked ? maps.length : Number(readSelectedValue(message, InteractionComponent.CountSelect));
  if (!MAP_COUNTS.includes(count)) {
    throw new Error("Map count was not selected");
  }

  const playlist = locked
    ? readPlaylistFromEmbed(message)
    : z.enum(MapsPlaylistType).parse(readSelectedValue(message, InteractionComponent.PlaylistSelect));
  const format = locked
    ? readFormatFromEmbed(message)
    : z.enum(MapsFormatType).parse(readSelectedValue(message, InteractionComponent.FormatSelect));
  if (maps.length !== 0 && maps.length !== count) {
    throw new Error("Map list does not match the selected count");
  }

  return {
    ...readAttributionFromEmbed(message),
    locked,
    plan: locked ? readPlanFromEmbed(message) : undefined,
    autoQueueNumber: readAutoQueueNumberFromEmbed(message),
    count,
    playlist,
    format,
    maps,
  };
}
