import { describe, it, beforeEach, expect, vi } from "vitest";
import type {
  APIInteractionResponseChannelMessageWithSource,
  APIApplicationCommandInteraction,
  APIMessageComponentButtonInteraction,
  APIInteractionResponseCallbackData,
  APIActionRowComponent,
  APIMessageTopLevelComponent,
  APIButtonComponentWithCustomId,
  APIMessageComponentSelectMenuInteraction,
  APIStringSelectComponent,
} from "discord-api-types/v10";
import {
  ApplicationCommandOptionType,
  ApplicationCommandType,
  InteractionType,
  Locale,
  ComponentType,
  MessageFlags,
  ButtonStyle,
  InteractionResponseType,
} from "discord-api-types/v10";
import { MapsCommand, PlaylistType, InteractionComponent } from "../maps.mjs";
import { installFakeServicesWith } from "../../../services/fakes/services.mjs";
import type { Services } from "../../../services/install.mjs";
import { aFakeEnvWith } from "../../../base/fakes/env.fake.mjs";
import {
  apiMessage,
  fakeBaseAPIApplicationCommandInteraction,
  fakeButtonClickInteraction,
} from "../../../services/discord/fakes/data.mjs";
import { Preconditions } from "../../../base/preconditions.mjs";

function aFakeMapsInteractionWith(
  options: { name: string; value: unknown; type: number }[] = [],
): APIApplicationCommandInteraction {
  const applicationCommandInteractionMap: APIApplicationCommandInteraction = {
    ...fakeBaseAPIApplicationCommandInteraction,
    type: InteractionType.ApplicationCommand,
    guild: {
      features: [],
      id: "fake-guild-id",
      locale: Locale.EnglishUS,
    },
    guild_id: "fake-guild-id",
    data: {
      id: "fake-cmd-id",
      name: "maps",
      options,
      resolved: {},
      type: ApplicationCommandType.ChatInput,
    },
  };

  return applicationCommandInteractionMap;
}

function getButtonRow(
  components: APIMessageTopLevelComponent[] | undefined,
): APIActionRowComponent<APIButtonComponentWithCustomId> {
  return components?.find(
    (c) =>
      c.type === ComponentType.ActionRow &&
      c.components.every((subComponent) => subComponent.type === ComponentType.Button),
  ) as APIActionRowComponent<APIButtonComponentWithCustomId>;
}

function getButtonById(
  row: APIActionRowComponent<APIButtonComponentWithCustomId> | undefined,
  custom_id: string,
): APIButtonComponentWithCustomId {
  return Preconditions.checkExists(row?.components.find((b) => b.custom_id === custom_id));
}

function getSelectMenu(components: APIMessageTopLevelComponent[] | undefined): APIStringSelectComponent {
  for (const row of components ?? []) {
    if (row.type === ComponentType.ActionRow && "components" in row && Array.isArray(row.components)) {
      for (const c of row.components) {
        if (c.type === ComponentType.StringSelect) {
          return c;
        }
      }
    }
  }

  throw new Error("No select menu found in components");
}

describe("MapsCommand", () => {
  let command: MapsCommand;
  let services: Services;
  const env = aFakeEnvWith();

  beforeEach(() => {
    services = installFakeServicesWith({ env });
    command = new MapsCommand(services, env);
    vi.spyOn(services.logService, "error").mockImplementation(() => undefined);
    vi.spyOn(services.discordService, "getEmojiFromName").mockReturnValue(":GameCoachGG:");
  });

  describe("/maps basic usage", () => {
    it("returns a set of 5 maps by default", () => {
      const interaction = aFakeMapsInteractionWith();
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      expect(data).toHaveProperty("embeds");

      const embed = data.embeds?.[0];
      expect(embed).toBeDefined();
      expect(embed?.title).toContain(`Maps: ${PlaylistType.HcsCurrent}`);
      expect(embed?.fields?.length).toBeGreaterThanOrEqual(3); // #, Mode, Map columns + attribution
      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);
      expect(embed?.fields?.some((f) => f.value.includes("Generated by"))).toBe(true);
      expect(data.components?.[0]?.type).toBe(ComponentType.ActionRow);

      const buttonRow = getButtonRow(data.components);
      expect(buttonRow).toBeDefined();
      expect(buttonRow.components).toHaveLength(4);
      expect(getButtonById(buttonRow, InteractionComponent.Roll5).style).toBe(ButtonStyle.Primary);
    });

    it("returns a set of 3 maps when count=3", () => {
      const interaction = aFakeMapsInteractionWith([
        { name: "count", value: 3, type: ApplicationCommandOptionType.Integer },
      ]);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(3);

      const buttonRow3 = getButtonRow(data.components);
      expect(getButtonById(buttonRow3, InteractionComponent.Roll3).style).toBe(ButtonStyle.Primary);
    });

    it("returns a set of 7 maps when count=7", () => {
      const interaction = aFakeMapsInteractionWith([
        { name: "count", value: 7, type: ApplicationCommandOptionType.Integer },
      ]);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(7);

      const buttonRow7 = getButtonRow(data.components);
      expect(getButtonById(buttonRow7, InteractionComponent.Roll7).style).toBe(ButtonStyle.Primary);
    });
  });

  describe("/maps playlist option", () => {
    it("returns maps from the historical playlist when selected", () => {
      const interaction = aFakeMapsInteractionWith([
        { name: "playlist", value: PlaylistType.HcsHistorical, type: ApplicationCommandOptionType.String },
      ]);

      const { response } = command.execute(interaction);

      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed).toBeDefined();
      expect(embed?.title).toContain(PlaylistType.HcsHistorical);
      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);
    });

    it("returns maps from the current playlist by default", () => {
      const interaction = aFakeMapsInteractionWith();

      const { response } = command.execute(interaction);

      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed).toBeDefined();
      expect(embed?.title).toContain(PlaylistType.HcsCurrent);
      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);
    });
  });

  describe("/maps button interaction", () => {
    function aFakeButtonInteraction(
      custom_id: string,
      playlist: PlaylistType = PlaylistType.HcsCurrent,
    ): APIMessageComponentButtonInteraction {
      return {
        ...fakeButtonClickInteraction,
        data: {
          ...fakeButtonClickInteraction.data,
          custom_id,
        },
        message: {
          ...fakeButtonClickInteraction.message,
          embeds: [{ title: `Maps: ${playlist}` }],
        },
      };
    }

    it("regenerates maps with correct count and playlist when button is pressed", () => {
      const interaction = aFakeButtonInteraction(InteractionComponent.Roll3, PlaylistType.HcsHistorical);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed?.title).toContain(PlaylistType.HcsHistorical);
      expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(3);

      const buttonRowHist = getButtonRow(data.components);
      expect(getButtonById(buttonRowHist, InteractionComponent.Roll3).style).toBe(ButtonStyle.Primary);
    });

    it("throws for unknown button id", () => {
      const interaction = aFakeButtonInteraction("btn_maps_roll_unknown");
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;

      expect(data.content).toMatch(/Unreachable code with specified value/);
      expect(data.flags).toBe(MessageFlags.Ephemeral);
    });

    it("throws for unknown playlist in embed", () => {
      const interaction = aFakeButtonInteraction(InteractionComponent.Roll1, "NotAPlaylist" as PlaylistType);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;

      expect(data.content).toMatch(/Unknown playlist type in embed/);
      expect(data.flags).toBe(MessageFlags.Ephemeral);
    });

    it("returns DeferredMessageUpdate and jobToComplete for Initiate button", async () => {
      const interaction = aFakeButtonInteraction(InteractionComponent.Initiate);
      const { response, jobToComplete } = command.execute(interaction);
      expect(response).toEqual({ type: InteractionResponseType.DeferredMessageUpdate });
      expect(typeof jobToComplete).toBe("function");

      const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);
      await jobToComplete?.();
      const [channelId, data] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
      expect(channelId).toBe(interaction.channel.id);
      expect(data.embeds?.[0]?.title).toContain("Maps: HCS - current");

      const actionRow = getButtonRow(data.components);
      expect(actionRow.components).toHaveLength(4);
    });
  });

  describe("/maps playlist select interaction", () => {
    function aFakePlaylistSelectInteraction(
      playlist: PlaylistType,
      count: 1 | 3 | 5 | 7 = 5,
    ): APIMessageComponentSelectMenuInteraction {
      // Simulate a select menu interaction with the given playlist and a message with the correct button row
      const buttonRow: APIMessageTopLevelComponent = {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll1,
            style: count === 1 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll3,
            style: count === 3 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll5,
            style: count === 5 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll7,
            style: count === 7 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
        ],
      };
      return {
        ...fakeButtonClickInteraction,
        data: {
          custom_id: InteractionComponent.MapsPlaylistSelect,
          component_type: ComponentType.StringSelect,
          values: [playlist],
        },
        message: {
          ...fakeButtonClickInteraction.message,
          components: [buttonRow],
          embeds: [{ title: `Maps: ${PlaylistType.HcsCurrent}` }],
        },
      };
    }

    it("updates the embed and buttons when playlist is switched to historical", () => {
      const interaction = aFakePlaylistSelectInteraction(PlaylistType.HcsHistorical, 3);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];

      expect(embed?.title).toContain(PlaylistType.HcsHistorical);

      const buttonRow = getButtonRow(data.components);
      expect(getButtonById(buttonRow, InteractionComponent.Roll3).style).toBe(ButtonStyle.Primary);

      const select = getSelectMenu(data.components);
      expect(select.custom_id).toBe(InteractionComponent.MapsPlaylistSelect);
      expect(select.options.find((o) => o.value === String(PlaylistType.HcsHistorical))?.default).toBe(true);
      expect(select.options.find((o) => o.value === String(PlaylistType.HcsCurrent))?.default).toBe(false);
    });

    it("updates the embed and buttons when playlist is switched to current", () => {
      const interaction = aFakePlaylistSelectInteraction(PlaylistType.HcsCurrent, 7);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];
      expect(embed?.title).toContain(PlaylistType.HcsCurrent);

      const buttonRow = getButtonRow(data.components);
      expect(getButtonById(buttonRow, InteractionComponent.Roll7).style).toBe(ButtonStyle.Primary);

      const select = getSelectMenu(data.components);
      expect(select.custom_id).toBe(InteractionComponent.MapsPlaylistSelect);
      expect(select.options.find((o) => o.value === String(PlaylistType.HcsCurrent))?.default).toBe(true);
      expect(select.options.find((o) => o.value === String(PlaylistType.HcsHistorical))?.default).toBe(false);
    });
  });

  describe("/maps uniqueness and spread", () => {
    it("does not repeat maps in a short series", () => {
      const interaction = aFakeMapsInteractionWith([
        { name: "count", value: 3, type: ApplicationCommandOptionType.Integer },
      ]);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];
      const maps = embed?.fields?.[2]?.value.split("\n") ?? [];
      const uniqueMaps = new Set(maps);

      expect(uniqueMaps.size).toBe(maps.length);
    });

    it("allows repeats only after all maps are used in a long series", () => {
      const interaction = aFakeMapsInteractionWith([
        { name: "count", value: 7, type: ApplicationCommandOptionType.Integer },
      ]);
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;
      const embed = data.embeds?.[0];
      const maps = embed?.fields?.[2]?.value.split("\n") ?? [];
      const uniqueMaps = new Set(maps);

      expect(uniqueMaps.size).toBeLessThanOrEqual(maps.length);
      expect(uniqueMaps.size).toBeGreaterThanOrEqual(5);
    });
  });

  describe("/maps error handling", () => {
    it("returns an error message if something throws", () => {
      vi.spyOn(Object.getPrototypeOf(command), "generateHcsSet").mockImplementation(() => {
        throw new Error("fail");
      });

      const interaction = aFakeMapsInteractionWith();
      const { response } = command.execute(interaction);
      const { data } = response as APIInteractionResponseChannelMessageWithSource;

      expect(data.content).toMatch(/fail/);
      expect(data.flags).toBe(MessageFlags.Ephemeral);
    });
  });
});
