import type { MockInstance } from "vitest";
import { describe, it, beforeEach, expect, vi } from "vitest";
import type {
  APIInteractionResponse,
  APIApplicationCommandInteraction,
  APIMessageComponentButtonInteraction,
  APIInteractionResponseCallbackData,
  APIActionRowComponent,
  APIMessageTopLevelComponent,
  APIButtonComponentWithCustomId,
  APIMessageComponentSelectMenuInteraction,
  APIStringSelectComponent,
  APIEmbed,
  APIMessage,
} from "discord-api-types/v10";
import {
  ApplicationCommandOptionType,
  ApplicationCommandType,
  InteractionType,
  Locale,
  ComponentType,
  MessageFlags,
  InteractionResponseType,
} from "discord-api-types/v10";
import type { MapMode } from "../../../services/halo/hcs";
import { MapsCommand } from "../maps";
import { GAMECOACH_GG_URLS } from "../gamecoachgg";
import { InteractionComponent, MapsEmbed } from "../../../embeds/maps-embed";
import { MAP_COUNTS } from "../../../services/halo/hcs";
import { installFakeServicesWith } from "../../../services/fakes/services";
import type { Services } from "../../../services/install";
import { aFakeEnvWith } from "../../../base/fakes/env.fake";
import {
  apiMessage,
  discordNeatQueueData,
  fakeBaseAPIApplicationCommandInteraction,
} from "../../../services/discord/fakes/data";
import { MapsFormatType, MapsPlaylistType } from "../../../services/database/types/guild_config";

function aFakeMapsInteractionWith(
  options: { name: string; value: unknown; type: number }[] = [],
): APIApplicationCommandInteraction {
  return {
    ...fakeBaseAPIApplicationCommandInteraction,
    type: InteractionType.ApplicationCommand,
    guild: {
      ...fakeBaseAPIApplicationCommandInteraction.guild,
      id: "fake-guild-id",
      locale: Locale.EnglishUS,
      features: [], // Ensure features is always present
    },
    guild_id: "fake-guild-id",
    data: {
      id: "fake-cmd-id",
      name: "maps",
      options,
      resolved: {},
      type: ApplicationCommandType.ChatInput,
    },
  };
}

function getButtonRow(
  components: APIMessageTopLevelComponent[] | undefined,
): APIActionRowComponent<APIButtonComponentWithCustomId> {
  return components?.find(
    (c) =>
      c.type === ComponentType.ActionRow &&
      c.components.every((subComponent) => subComponent.type === ComponentType.Button),
  ) as APIActionRowComponent<APIButtonComponentWithCustomId>;
}

function getSelectMenu(
  components: APIMessageTopLevelComponent[] | undefined,
  customId?: string,
): APIStringSelectComponent {
  for (const row of components ?? []) {
    if (row.type === ComponentType.ActionRow && "components" in row && Array.isArray(row.components)) {
      for (const c of row.components) {
        if (c.type === ComponentType.StringSelect && (customId === undefined || c.custom_id === customId)) {
          return c;
        }
      }
    }
  }

  throw new Error("No select menu found in components");
}

function aFakeMapsMessage({
  playlist = MapsPlaylistType.HCS_CURRENT,
  format = MapsFormatType.HCS,
  count = 5,
  selectedPlaylist,
  selectedFormat,
}: {
  playlist?: MapsPlaylistType;
  format?: MapsFormatType;
  count?: number;
  selectedPlaylist?: MapsPlaylistType | undefined;
  selectedFormat?: MapsFormatType | undefined;
}): {
  embeds: APIEmbed[];
  components: APIMessageTopLevelComponent[];
} {
  const lines = Array(count)
    .fill(0)
    .map((_, i) => String(i + 1));
  return {
    embeds: [
      {
        title: `Maps: ${format}`,
        fields: [
          { name: "#", value: lines.join("\n"), inline: true },
          { name: "Mode", value: Array(count).fill("Slayer").join("\n"), inline: true },
          {
            name: "Map",
            value: Array(count)
              .fill("[Live Fire :GameCoachGG:](https://gamecoach.gg/esports/haloinfinite/livefire)")
              .join("\n"),
            inline: true,
          },
          { name: "", value: "-# Generated by <@user123>" },
        ],
      },
    ],
    components: [
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.CountSelect,
            options: MAP_COUNTS.map((value) => ({
              label: value.toString(),
              value: value.toString(),
              default: value === count,
            })),
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.PlaylistSelect,
            options: [
              {
                label: MapsPlaylistType.HCS_CURRENT,
                value: MapsPlaylistType.HCS_CURRENT,
                default: (selectedPlaylist ?? playlist) === MapsPlaylistType.HCS_CURRENT,
              },
              {
                label: `${MapsPlaylistType.HCS_HISTORICAL} (all maps + modes played in any HCS major)`,
                value: MapsPlaylistType.HCS_HISTORICAL,
                default: (selectedPlaylist ?? playlist) === MapsPlaylistType.HCS_HISTORICAL,
              },
            ],
            placeholder: "Select a playlist",
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.FormatSelect,
            options: [
              {
                label: MapsFormatType.HCS,
                value: MapsFormatType.HCS,
                default: (selectedFormat ?? format) === MapsFormatType.HCS,
              },
              {
                label: MapsFormatType.RANDOM,
                value: MapsFormatType.RANDOM,
                default: (selectedFormat ?? format) === MapsFormatType.RANDOM,
              },
              {
                label: MapsFormatType.OBJECTIVE,
                value: MapsFormatType.OBJECTIVE,
                default: (selectedFormat ?? format) === MapsFormatType.OBJECTIVE,
              },
              {
                label: MapsFormatType.SLAYER,
                value: MapsFormatType.SLAYER,
                default: (selectedFormat ?? format) === MapsFormatType.SLAYER,
              },
            ],
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Regenerate,
            style: 1,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Repost,
            style: 2,
          },
        ],
      },
    ],
  };
}

function aFakeApiMessage({
  playlist = MapsPlaylistType.HCS_CURRENT,
  format = MapsFormatType.HCS,
  count = 5,
  selectedPlaylist,
  selectedFormat,
}: {
  playlist?: MapsPlaylistType;
  format?: MapsFormatType | undefined;
  count?: number;
  selectedPlaylist?: MapsPlaylistType | undefined;
  selectedFormat?: MapsFormatType | undefined;
}): APIMessage {
  return {
    ...apiMessage,
    embeds: aFakeMapsMessage({ playlist, format, count, selectedPlaylist, selectedFormat }).embeds,
    components: aFakeMapsMessage({ playlist, format, count, selectedPlaylist, selectedFormat }).components,
  };
}

function aFakeButtonInteraction(
  customId: string,
  playlist: MapsPlaylistType = MapsPlaylistType.HCS_CURRENT,
  format: MapsFormatType = MapsFormatType.HCS,
  count = 5,
): APIMessageComponentButtonInteraction {
  return {
    ...fakeBaseAPIApplicationCommandInteraction,
    id: "fake-interaction-id",
    guild_id: "fake-guild-id",
    type: InteractionType.MessageComponent,
    data: {
      component_type: ComponentType.Button,
      custom_id: customId,
    },
    message: aFakeApiMessage({ playlist, format, count }),
  };
}

function aFakePlaylistSelectInteraction(
  selectedPlaylist: MapsPlaylistType,
  count = 5,
  playlist: MapsPlaylistType = MapsPlaylistType.HCS_CURRENT,
  format: MapsFormatType = MapsFormatType.HCS,
): APIMessageComponentSelectMenuInteraction {
  return {
    ...fakeBaseAPIApplicationCommandInteraction,
    id: "fake-interaction-id",
    type: InteractionType.MessageComponent,
    data: {
      component_type: ComponentType.StringSelect,
      custom_id: InteractionComponent.PlaylistSelect,
      values: [selectedPlaylist],
    },
    message: aFakeApiMessage({ playlist, format, count, selectedPlaylist }),
  };
}

function aFakeCountSelectInteraction(selectedCount: number): APIMessageComponentSelectMenuInteraction {
  return {
    ...fakeBaseAPIApplicationCommandInteraction,
    id: "fake-interaction-id",
    type: InteractionType.MessageComponent,
    data: {
      component_type: ComponentType.StringSelect,
      custom_id: InteractionComponent.CountSelect,
      values: [selectedCount.toString()],
    },
    message: aFakeApiMessage({}),
  };
}

function aFakeFormatSelectInteraction(
  selectedFormat: MapsFormatType,
  count = 5,
  playlist: MapsPlaylistType = MapsPlaylistType.HCS_CURRENT,
  format: MapsFormatType = MapsFormatType.HCS,
): APIMessageComponentSelectMenuInteraction {
  return {
    ...fakeBaseAPIApplicationCommandInteraction,
    id: "fake-interaction-id",
    type: InteractionType.MessageComponent,
    data: {
      component_type: ComponentType.StringSelect,
      custom_id: InteractionComponent.FormatSelect,
      values: [selectedFormat],
    },
    message: aFakeApiMessage({ playlist, format, count, selectedFormat }),
  };
}

describe("MapsCommand", () => {
  let command: MapsCommand;
  let services: Services;
  let env: Env;
  let updateDeferredReplySpy: MockInstance;
  const mockMaps = [
    { mode: "Slayer" as MapMode, map: "Live Fire" },
    { mode: "Oddball" as MapMode, map: "Streets" },
    { mode: "Strongholds" as MapMode, map: "Bazaar" },
    { mode: "CTF" as MapMode, map: "Aquarius" },
    { mode: "Slayer" as MapMode, map: "Recharge" },
  ];

  beforeEach(() => {
    services = installFakeServicesWith();
    env = aFakeEnvWith();
    command = new MapsCommand(services, env);

    updateDeferredReplySpy = vi.spyOn(services.discordService, "updateDeferredReply").mockResolvedValue(apiMessage);
    vi.spyOn(services.logService, "error").mockImplementation(() => undefined);
    vi.spyOn(services.discordService, "getEmojiFromName").mockReturnValue(":GameCoachGG:");
    vi.spyOn(services.haloService, "generateMaps").mockResolvedValue(mockMaps);
    vi.spyOn(services.haloService, "getMapModesForPlaylist").mockResolvedValue([
      "Slayer",
      "Capture the Flag",
      "Strongholds",
      "Oddball",
      "King of the Hill",
    ]);
  });

  describe("execute(): application command", () => {
    it("returns response and jobToComplete", () => {
      const interaction = aFakeMapsInteractionWith();

      const { response, jobToComplete } = command.execute(interaction);

      expect(response).toEqual<APIInteractionResponse>({
        type: InteractionResponseType.DeferredChannelMessageWithSource,
      });
      expect(jobToComplete).toBeInstanceOf(Function);
    });

    describe("jobToComplete", () => {
      let jobToComplete: (() => Promise<void>) | undefined;

      beforeEach(() => {
        const interaction = aFakeMapsInteractionWith();
        const { jobToComplete: jtc } = command.execute(interaction);
        jobToComplete = jtc;
      });

      it("calls discordService.updateDeferredReply with maps embed", async () => {
        const appDataPutSpy = vi.spyOn(env.APP_DATA, "put");
        await jobToComplete?.();

        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
        expect(updateDeferredReplySpy.mock.lastCall).toMatchSnapshot();
        expect(appDataPutSpy).not.toHaveBeenCalled();
      });

      it("renders the mock maps in the embed", async () => {
        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(data).toHaveProperty("embeds");

        const embed = data.embeds?.[0];
        expect(embed).toBeDefined();
        expect(embed?.fields?.length).toBeGreaterThanOrEqual(3);

        const modes = embed?.fields?.[1]?.value.split("\n") ?? [];
        const maps = embed?.fields?.[2]?.value.split("\n") ?? [];
        expect(modes).toEqual(["Slayer", "Oddball", "Strongholds", "CTF", "Slayer"]);
        expect(maps).toEqual([
          "[Live Fire :GameCoachGG:](https://gamecoach.gg/esports/haloinfinite/livefire)",
          "[Streets :GameCoachGG:](https://gamecoach.gg/esports/haloinfinite/streets)",
          "Bazaar",
          "[Aquarius :GameCoachGG:](https://gamecoach.gg/esports/haloinfinite/aquarius)",
          "[Recharge :GameCoachGG:](https://gamecoach.gg/esports/haloinfinite/recharge)",
        ]);
      });
    });

    it("renders Slayer as the format for an initial Slayer-only message", async () => {
      vi.spyOn(services.haloService, "getMapModesForPlaylist").mockResolvedValue(["Slayer"]);
      const interaction = aFakeMapsInteractionWith();
      const { jobToComplete } = command.execute(interaction);

      await jobToComplete?.();

      const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
      const formatSelect = getSelectMenu(data.components, InteractionComponent.FormatSelect);
      expect(formatSelect.options.find((option) => option.default === true)?.value).toBe(MapsFormatType.SLAYER);
    });
  });

  describe("execute(): application command with options", () => {
    describe("playlist option", () => {
      it("returns deferred response and jobToComplete for historical playlist", () => {
        const interaction = aFakeMapsInteractionWith([
          { name: "playlist", value: MapsPlaylistType.HCS_HISTORICAL, type: ApplicationCommandOptionType.String },
        ]);

        const { response, jobToComplete } = command.execute(interaction);

        expect(response).toEqual<APIInteractionResponse>({
          type: InteractionResponseType.DeferredChannelMessageWithSource,
        });
        expect(jobToComplete).toBeInstanceOf(Function);
      });

      it("calls updateDeferredReply with historical playlist embed", async () => {
        const interaction = aFakeMapsInteractionWith([
          { name: "playlist", value: MapsPlaylistType.HCS_HISTORICAL, type: ApplicationCommandOptionType.String },
        ]);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toContain(MapsPlaylistType.HCS_HISTORICAL);
        expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);
      });

      it("calls updateDeferredReply with current playlist embed by default", async () => {
        const interaction = aFakeMapsInteractionWith();
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toContain(MapsPlaylistType.HCS_CURRENT);
        expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);
      });
    });
  });

  describe("execute(): message component interactions", () => {
    describe("count select", () => {
      it("generates 13 maps from the selected count", async () => {
        const generateMapsSpy = vi.spyOn(services.haloService, "generateMaps");
        generateMapsSpy.mockResolvedValue(
          Array.from({ length: 13 }, (_, index) => ({
            mode: "Slayer",
            map: `Map ${(index + 1).toString()}`,
          })),
        );
        const interaction = aFakeCountSelectInteraction(13);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(generateMapsSpy).toHaveBeenCalledWith({
          count: 13,
          playlist: MapsPlaylistType.HCS_CURRENT,
          format: MapsFormatType.HCS,
        });
        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("13");
      });
    });

    describe("button interactions", () => {
      it("returns deferred response and jobToComplete for roll button", () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Regenerate, MapsPlaylistType.HCS_HISTORICAL);

        const { response, jobToComplete } = command.execute(interaction);

        expect(response).toEqual<APIInteractionResponse>({
          type: InteractionResponseType.DeferredMessageUpdate,
        });
        expect(jobToComplete).toBeInstanceOf(Function);
      });

      it("calls updateDeferredReply with regenerated maps", async () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Regenerate, MapsPlaylistType.HCS_HISTORICAL);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toBeDefined();
        expect(embed?.title ?? "").toContain(MapsPlaylistType.HCS_HISTORICAL);
        expect(embed?.fields?.[0]?.value.split("\n")).toHaveLength(5);

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("5");
      });

      it("calls updateDeferredReply for non-initiate roll buttons", async () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Regenerate);
        const { jobToComplete } = command.execute(interaction);

        const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);

        await jobToComplete?.();

        expect(updateDeferredReplySpy).toHaveBeenCalledTimes(1);
        expect(createMessageSpy).not.toHaveBeenCalled();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toBeDefined();

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("5");
      });

      it("confirms the maps in the active queue tracker", async () => {
        const getCachedQueue = vi.spyOn(services.discordService, "getActiveQueueNumber").mockResolvedValue(99);
        const getTeams = vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        const setPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "setPlannedMaps").mockResolvedValue();
        const interaction = aFakeButtonInteraction(InteractionComponent.Confirm);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(setPlannedMapsSpy).toHaveBeenCalledWith(
          expect.objectContaining({ guildId: "fake-guild-id", channelId: interaction.channel.id, queueNumber: 42 }),
          Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
          expect.any(String),
        );
        expect(getTeams).toHaveBeenCalledWith("fake-guild-id", interaction.channel.id);
        expect(getCachedQueue).not.toHaveBeenCalled();
        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(data.embeds?.[0]?.footer?.text).toMatch(/^Queue: 42 \| Plan: [\da-f-]+$/);
        const confirmCustomId: string = InteractionComponent.Confirm;
        const confirmButton = getButtonRow(data.components).components.find(
          (component) => "custom_id" in component && component.custom_id === confirmCustomId,
        );
        expect(data.components).toHaveLength(1);
        expect(confirmButton).toBeUndefined();
        expect(JSON.stringify(data.components)).toContain(InteractionComponent.Clear);
        expect(JSON.stringify(data.components)).toContain(InteractionComponent.Repost);
        expect(JSON.stringify(data.components)).not.toContain(InteractionComponent.CountSelect);
        expect(JSON.stringify(data.components)).not.toContain(InteractionComponent.Regenerate);
      });

      it("attributes confirmation to the user who clicks Confirm", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue(null);
        const interaction = aFakeButtonInteraction(InteractionComponent.Confirm);
        if (interaction.member != null) {
          interaction.member.user.id = "confirming-user";
        }

        await command.execute(interaction).jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(data.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Confirmed by <@confirming-user> | Format: HCS");
      });

      it("rolls back its queue plan when publishing the confirmation fails", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        const setPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "setPlannedMaps").mockResolvedValue();
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockResolvedValue(true);
        const error = new Error("Discord update failed");
        updateDeferredReplySpy.mockRejectedValueOnce(error);
        const interaction = aFakeButtonInteraction(InteractionComponent.Confirm);

        await command.execute(interaction).jobToComplete?.();

        expect(clearPlannedMapsSpy).toHaveBeenCalledOnce();
        expect(clearPlannedMapsSpy).toHaveBeenCalledWith(
          expect.objectContaining({ queueNumber: 42, channelId: interaction.channel.id }),
          setPlannedMapsSpy.mock.calls[0]?.[2],
        );
        expect(updateDeferredReplySpy).toHaveBeenCalledTimes(2);
        const [, response] = updateDeferredReplySpy.mock.calls[1] as [string, APIInteractionResponseCallbackData];
        expect(response.embeds?.[0]?.description).toContain("An unexpected error has occurred");
      });

      it("does not roll back another plan when publishing confirmation fails", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        vi.spyOn(services.liveTrackerService, "setPlannedMaps").mockResolvedValue();
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockResolvedValue(false);
        updateDeferredReplySpy.mockRejectedValueOnce(new Error("Discord update failed"));

        await command.execute(aFakeButtonInteraction(InteractionComponent.Confirm)).jobToComplete?.();

        expect(clearPlannedMapsSpy).toHaveBeenCalledOnce();
        expect(updateDeferredReplySpy).toHaveBeenCalledTimes(2);
      });

      it("logs rollback failures when publishing confirmation fails", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        vi.spyOn(services.liveTrackerService, "setPlannedMaps").mockResolvedValue();
        const rollbackError = new Error("Rollback failed");
        vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockRejectedValue(rollbackError);
        const publishError = new Error("Discord update failed");
        updateDeferredReplySpy.mockRejectedValueOnce(publishError);
        const logErrorSpy = vi.spyOn(services.logService, "error");

        await command.execute(aFakeButtonInteraction(InteractionComponent.Confirm)).jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(rollbackError);
        expect(logErrorSpy).toHaveBeenCalledWith(publishError);
        expect(updateDeferredReplySpy).toHaveBeenCalledTimes(2);
      });

      it("confirms an ad-hoc maps message without writing to a tracker", async () => {
        vi.spyOn(services.discordService, "getActiveQueueNumber").mockResolvedValue(99);
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue(null);
        const setPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "setPlannedMaps");
        const interaction = aFakeButtonInteraction(InteractionComponent.Confirm);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(setPlannedMapsSpy).not.toHaveBeenCalled();
        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
      });

      it("does not persist a plan when resolving playlist modes fails on confirmation", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        vi.spyOn(services.haloService, "getMapModesForPlaylist").mockRejectedValue(new Error("Modes unavailable"));
        const setPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "setPlannedMaps");

        await command.execute(aFakeButtonInteraction(InteractionComponent.Confirm)).jobToComplete?.();

        expect(setPlannedMapsSpy).not.toHaveBeenCalled();
        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
        const [, response] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(response.embeds?.[0]?.description).toContain("An unexpected error has occurred");
      });

      it("requires a second confirmation before clearing the active queue plan", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        const logErrorSpy = vi.spyOn(services.logService, "error");
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockResolvedValue(true);
        const clearInteraction = aFakeButtonInteraction(InteractionComponent.Clear);
        if (clearInteraction.member != null) {
          clearInteraction.member.user.id = "clear-initiator";
        }
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
            plan: { queueNumber: 42, token: "00000000-0000-4000-8000-000000000001" },
          },
        ).toMessageData();
        clearInteraction.message.embeds = lockedMessage.embeds ?? [];
        clearInteraction.message.components = lockedMessage.components ?? [];
        const { jobToComplete: clearJob } = command.execute(clearInteraction);

        await clearJob?.();

        expect(clearPlannedMapsSpy).not.toHaveBeenCalled();
        expect(logErrorSpy).not.toHaveBeenCalled();
        const [, confirmationData] = updateDeferredReplySpy.mock.calls[0] as [
          string,
          APIInteractionResponseCallbackData,
        ];
        expect(JSON.stringify(confirmationData.components)).toContain(InteractionComponent.ConfirmClear);
        expect(confirmationData.embeds).toHaveLength(2);
        expect(confirmationData.embeds?.[1]?.title).toBe("Clear planned maps?");
        expect(confirmationData.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Confirmed by <@user123> | Format: HCS");
        expect(confirmationData.embeds?.[0]?.footer?.text).toBe(
          "Queue: 42 | Plan: 00000000-0000-4000-8000-000000000001",
        );
        expect(confirmationData.embeds?.[1]?.fields?.[0]?.value).toBe("-# Clear initiated by <@clear-initiator>");
        expect(getButtonRow(confirmationData.components).components.map((button) => button.custom_id)).toEqual([
          InteractionComponent.ConfirmClear,
          InteractionComponent.CancelClear,
        ]);

        const confirmInteraction = aFakeButtonInteraction(InteractionComponent.ConfirmClear);
        if (confirmInteraction.member != null) {
          confirmInteraction.member.user.id = "clear-confirmer";
        }
        confirmInteraction.message.embeds = confirmationData.embeds ?? [];
        confirmInteraction.message.components = confirmationData.components ?? [];
        const { jobToComplete: confirmJob } = command.execute(confirmInteraction);

        await confirmJob?.();

        expect(clearPlannedMapsSpy).toHaveBeenCalledWith(
          expect.objectContaining({
            guildId: "fake-guild-id",
            channelId: confirmInteraction.channel.id,
            queueNumber: 42,
          }),
          "00000000-0000-4000-8000-000000000001",
        );
        const [, data] = updateDeferredReplySpy.mock.calls[1] as [string, APIInteractionResponseCallbackData];
        expect(data.embeds?.[0]?.description).toBe("No maps selected");
        expect(data.embeds?.[0]?.footer).toBeUndefined();
        expect(data.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Cleared by <@clear-confirmer> | Format: HCS");
        expect(data.components).toHaveLength(4);
      });

      it("clears an ad-hoc confirmed message locally even when a queue is now active", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps");
        const interaction = aFakeButtonInteraction(InteractionComponent.ConfirmClear);
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
          },
        ).toMessageData();
        interaction.message.embeds = lockedMessage.embeds ?? [];
        interaction.message.components = lockedMessage.components ?? [];
        await command.execute(interaction).jobToComplete?.();

        expect(clearPlannedMapsSpy).not.toHaveBeenCalled();
        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
      });

      it("keeps the stored plan when resolving playlist modes fails before clearing", async () => {
        vi.spyOn(services.haloService, "getMapModesForPlaylist").mockRejectedValue(new Error("Modes unavailable"));
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps");
        const interaction = aFakeButtonInteraction(InteractionComponent.ConfirmClear);
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
            plan: { queueNumber: 42, token: "00000000-0000-4000-8000-000000000001" },
          },
        ).toMessageData();
        interaction.message.embeds = lockedMessage.embeds ?? [];
        interaction.message.components = lockedMessage.components ?? [];

        await command.execute(interaction).jobToComplete?.();

        expect(clearPlannedMapsSpy).not.toHaveBeenCalled();
        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
        const [, response] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(response.embeds?.[0]?.description).toContain("An unexpected error has occurred");
      });

      it("does not clear a newer plan through an older confirmed message", async () => {
        vi.spyOn(services.discordService, "getTeamsFromQueueChannel").mockResolvedValue({
          ...discordNeatQueueData,
          queue: 42,
        });
        vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockResolvedValue(false);
        const interaction = aFakeButtonInteraction(InteractionComponent.ConfirmClear);
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
            plan: { queueNumber: 42, token: "00000000-0000-4000-8000-000000000001" },
          },
        ).toMessageData();
        interaction.message.embeds = lockedMessage.embeds ?? [];
        interaction.message.components = lockedMessage.components ?? [];
        await command.execute(interaction).jobToComplete?.();

        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
        const [, response] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(response.embeds?.[0]?.description).toBe("These maps are no longer the queue's current plan.");
      });

      it.each([null, 43])("clears the originating queue plan when the active queue is %s", async (activeQueue) => {
        const getTeams = vi
          .spyOn(services.discordService, "getTeamsFromQueueChannel")
          .mockResolvedValue(activeQueue == null ? null : { ...discordNeatQueueData, queue: activeQueue });
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps").mockResolvedValue(true);
        const interaction = aFakeButtonInteraction(InteractionComponent.ConfirmClear);
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
            plan: { queueNumber: 42, token: "00000000-0000-4000-8000-000000000001" },
          },
        ).toMessageData();
        interaction.message.embeds = lockedMessage.embeds ?? [];
        interaction.message.components = lockedMessage.components ?? [];
        await command.execute(interaction).jobToComplete?.();

        expect(clearPlannedMapsSpy).toHaveBeenCalledWith(
          expect.objectContaining({ queueNumber: 42, guildId: "fake-guild-id" }),
          "00000000-0000-4000-8000-000000000001",
        );
        expect(getTeams).not.toHaveBeenCalled();
        expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(data.embeds?.[0]?.description).toBe("No maps selected");
      });

      it("cancels clear confirmation without changing the locked map list", async () => {
        const clearPlannedMapsSpy = vi.spyOn(services.liveTrackerService, "clearPlannedMaps");
        const clearInteraction = aFakeButtonInteraction(InteractionComponent.Clear);
        if (clearInteraction.member != null) {
          clearInteraction.member.user.id = "clear-initiator";
        }
        const lockedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: Array.from({ length: 5 }, () => ({ mode: "Slayer", map: "Live Fire" })),
            availableModes: ["Slayer", "Capture the Flag"],
            locked: true,
          },
        ).toMessageData();
        clearInteraction.message.embeds = lockedMessage.embeds ?? [];
        clearInteraction.message.components = lockedMessage.components ?? [];
        const { jobToComplete: clearJob } = command.execute(clearInteraction);

        await clearJob?.();

        const [, confirmationData] = updateDeferredReplySpy.mock.calls[0] as [
          string,
          APIInteractionResponseCallbackData,
        ];
        const cancelInteraction = aFakeButtonInteraction(InteractionComponent.CancelClear);
        if (cancelInteraction.member != null) {
          cancelInteraction.member.user.id = "cancel-user";
        }
        cancelInteraction.message.embeds = confirmationData.embeds ?? [];
        cancelInteraction.message.components = confirmationData.components ?? [];
        const { jobToComplete: cancelJob } = command.execute(cancelInteraction);

        await cancelJob?.();

        expect(clearPlannedMapsSpy).not.toHaveBeenCalled();
        const [, restoredData] = updateDeferredReplySpy.mock.calls[1] as [string, APIInteractionResponseCallbackData];
        expect(restoredData.embeds).toHaveLength(1);
        expect(restoredData.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Confirmed by <@user123> | Format: HCS");
        expect(restoredData.components).toHaveLength(1);
        expect(JSON.stringify(restoredData.components)).toContain(InteractionComponent.Clear);
        expect(JSON.stringify(restoredData.components)).toContain(InteractionComponent.Repost);
      });

      it.each(["Generated by", "Cleared by"] as const)(
        "restores %s attribution after cancelling clear on an unlocked draft",
        async (attributionLabel) => {
          const interaction = aFakeButtonInteraction(InteractionComponent.CancelClear);
          if (interaction.member != null) {
            interaction.member.user.id = "cancel-user";
          }
          const original = new MapsEmbed(
            { discordService: services.discordService },
            {
              userId: "original-user",
              count: 5,
              playlist: MapsPlaylistType.HCS_CURRENT,
              format: MapsFormatType.HCS,
              maps: [],
              availableModes: ["Slayer", "Capture the Flag"],
              locked: false,
              attributionLabel,
            },
          ).toMessageData();
          interaction.message.embeds = original.embeds ?? [];
          interaction.message.components = original.components ?? [];

          await command.execute(interaction).jobToComplete?.();

          expect(updateDeferredReplySpy).toHaveBeenCalledOnce();
          const [, restoredData] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
          expect(restoredData.embeds?.[0]?.fields?.at(-1)?.value).toBe(
            `-# ${attributionLabel} <@original-user> | Format: HCS`,
          );
        },
      );

      it("throws for unknown button id", () => {
        const interaction = aFakeButtonInteraction("btn_maps_roll_unknown");

        const { response } = command.execute(interaction);

        expect(response.type).toBe(InteractionResponseType.ChannelMessageWithSource);
        if (response.type === InteractionResponseType.ChannelMessageWithSource) {
          expect(response.data.content).toMatch(/No handler found for component/);
          expect(response.data.flags).toBe(MessageFlags.Ephemeral);
        }
      });

      it("reports invalid map state in the message", async () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Regenerate);
        interaction.message.embeds = [];
        interaction.message.components = [];

        const { response, jobToComplete } = command.execute(interaction);

        expect(response.type).toBe(InteractionResponseType.DeferredMessageUpdate);
        const updateErrorSpy = vi.spyOn(services.discordService, "updateDeferredReplyWithError");
        await jobToComplete?.();
        expect(updateErrorSpy).toHaveBeenCalledWith(interaction.token, expect.any(Error));
      });

      describe("initiate button", () => {
        it("returns deferred response and jobToComplete", () => {
          const interaction = aFakeButtonInteraction(InteractionComponent.Initiate);

          const { response, jobToComplete } = command.execute(interaction);

          expect(response).toEqual<APIInteractionResponse>({
            type: InteractionResponseType.DeferredMessageUpdate,
          });
          expect(jobToComplete).toBeInstanceOf(Function);
        });

        it("calls createMessage instead of updateDeferredReply for initiate button", async () => {
          const interaction = aFakeButtonInteraction(InteractionComponent.Initiate);
          const { jobToComplete } = command.execute(interaction);

          const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);

          await jobToComplete?.();

          expect(createMessageSpy).toHaveBeenCalledTimes(1);
          expect(updateDeferredReplySpy).not.toHaveBeenCalled();

          const [channelId, data] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
          expect(channelId).toBe(interaction.channel.id);
          expect(data.embeds?.[0]?.title).toContain("Maps: LVT Pro League - Current");

          const actionRow = getButtonRow(data.components);
          expect(actionRow.components).toHaveLength(4);
        });

        it("renders Slayer as the format for an initiated Slayer-only message", async () => {
          const getMapModesSpy = vi
            .spyOn(services.haloService, "getMapModesForPlaylist")
            .mockReset()
            .mockResolvedValue(["Slayer"]);
          const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);
          const interaction = aFakeButtonInteraction(InteractionComponent.Initiate);
          const { jobToComplete } = command.execute(interaction);

          await jobToComplete?.();

          expect(getMapModesSpy).toHaveBeenCalledWith(MapsPlaylistType.HCS_CURRENT);
          const [, data] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
          const formatSelect = getSelectMenu(data.components, InteractionComponent.FormatSelect);
          expect(formatSelect.options.find((option) => option.default === true)?.value).toBe(MapsFormatType.SLAYER);
        });
      });
    });

    describe("repost button", () => {
      it("returns deferred response and jobToComplete", () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Repost);

        const { response, jobToComplete } = command.execute(interaction);

        expect(response).toEqual<APIInteractionResponse>({
          type: InteractionResponseType.DeferredMessageUpdate,
        });
        expect(jobToComplete).toBeInstanceOf(Function);
      });

      it("reposts the maps, then deletes the original message", async () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Repost);
        if (interaction.member != null) {
          interaction.member.user.id = "reposting-user";
        }
        const { jobToComplete } = command.execute(interaction);

        const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);
        const deleteMessageSpy = vi.spyOn(services.discordService, "deleteMessage").mockResolvedValue();

        await jobToComplete?.();

        expect(createMessageSpy).toHaveBeenCalledTimes(1);
        expect(deleteMessageSpy).toHaveBeenCalledTimes(1);

        const [channelId, data] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(channelId).toBe(interaction.channel.id);
        expect(data.embeds?.[0]?.title).toContain("Maps:");
        expect(data.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Generated by <@user123> | Format: HCS");

        const [delChannelId, delMessageId, delReason] = deleteMessageSpy.mock.calls[0] as [string, string, string];
        expect(delChannelId).toBe(interaction.channel.id);
        expect(delMessageId).toBe(interaction.message.id);
        expect(delReason).toBe("Reposting maps");
      });

      it("preserves cleared attribution when another user reposts an empty draft", async () => {
        const interaction = aFakeButtonInteraction(InteractionComponent.Repost);
        if (interaction.member != null) {
          interaction.member.user.id = "reposting-user";
        }
        const clearedMessage = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "clear-confirmer",
            count: 5,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: [],
            availableModes: ["Slayer", "Capture the Flag"],
            locked: false,
            attributionLabel: "Cleared by",
          },
        ).toMessageData();
        interaction.message.embeds = clearedMessage.embeds ?? [];
        interaction.message.components = clearedMessage.components ?? [];
        const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);
        vi.spyOn(services.discordService, "deleteMessage").mockResolvedValue();

        await command.execute(interaction).jobToComplete?.();

        expect(createMessageSpy).toHaveBeenCalledOnce();
        const [, data] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        expect(data.embeds?.[0]?.description).toBe("No maps selected");
        expect(data.embeds?.[0]?.fields?.at(-1)?.value).toBe("-# Cleared by <@clear-confirmer> | Format: HCS");
      });

      it("reposts all maps from split embed table fields", async () => {
        vi.spyOn(services.discordService, "getEmojiFromName").mockReturnValue(`:${"x".repeat(60)}:`);
        const sourceModes: MapMode[] = ["Slayer", "Oddball", "Strongholds", "Capture the Flag"];
        const sourceMapNames = Object.keys(GAMECOACH_GG_URLS);
        const sourceMaps: { mode: MapMode; map: string }[] = [];
        for (let index = 0; index < 13; index++) {
          const mode = sourceModes[index % sourceModes.length];
          const map = sourceMapNames[index % sourceMapNames.length];
          if (mode == null || map == null) {
            throw new Error("Expected map fixture value");
          }
          sourceMaps.push({ mode, map });
        }

        const sourceData = new MapsEmbed(
          { discordService: services.discordService },
          {
            userId: "user123",
            count: 13,
            playlist: MapsPlaylistType.HCS_CURRENT,
            format: MapsFormatType.HCS,
            maps: sourceMaps,
            availableModes: sourceModes,
          },
        ).toMessageData();
        const interaction = aFakeButtonInteraction(InteractionComponent.Repost);
        interaction.message.embeds = sourceData.embeds ?? [];
        interaction.message.components = sourceData.components ?? [];
        const { jobToComplete } = command.execute(interaction);
        const createMessageSpy = vi.spyOn(services.discordService, "createMessage").mockResolvedValue(apiMessage);

        await jobToComplete?.();

        const [, repostedData] = createMessageSpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const sourceFields = sourceData.embeds?.[0]?.fields?.filter((field) =>
          ["#", "Mode", "Map"].includes(field.name),
        );
        const repostedFields = repostedData.embeds?.[0]?.fields?.filter((field) =>
          ["#", "Mode", "Map"].includes(field.name),
        );
        expect(sourceFields).toHaveLength(6);
        expect(repostedFields).toEqual(sourceFields);
      });
    });

    describe("playlist select", () => {
      it("returns deferred response and jobToComplete", () => {
        const interaction = aFakePlaylistSelectInteraction(
          MapsPlaylistType.HCS_HISTORICAL,
          3,
          MapsPlaylistType.HCS_HISTORICAL,
        );

        const { response, jobToComplete } = command.execute(interaction);

        expect(response).toEqual<APIInteractionResponse>({
          type: InteractionResponseType.DeferredMessageUpdate,
        });
        expect(jobToComplete).toBeInstanceOf(Function);
      });

      it("calls updateDeferredReply when playlist is switched to historical", async () => {
        const interaction = aFakePlaylistSelectInteraction(
          MapsPlaylistType.HCS_HISTORICAL,
          3,
          MapsPlaylistType.HCS_HISTORICAL,
        );
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(typeof embed?.title).toBe("string");
        expect(embed?.title ?? "").toContain(MapsPlaylistType.HCS_HISTORICAL);

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("3");

        const select = getSelectMenu(data.components, InteractionComponent.PlaylistSelect);
        expect(select.custom_id).toBe(InteractionComponent.PlaylistSelect);
        expect(select.options.find((o) => o.value === MapsPlaylistType.HCS_HISTORICAL.toString())?.default).toBe(true);
        expect(select.options.find((o) => o.value === MapsPlaylistType.HCS_CURRENT.toString())?.default).toBe(false);
      });

      it("calls updateDeferredReply when playlist is switched to current", async () => {
        const interaction = aFakePlaylistSelectInteraction(
          MapsPlaylistType.HCS_CURRENT,
          7,
          MapsPlaylistType.HCS_CURRENT,
        );
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toBeDefined();
        expect(embed?.title).toContain(MapsPlaylistType.HCS_CURRENT);

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("7");

        const select = getSelectMenu(data.components, InteractionComponent.PlaylistSelect);
        expect(select.custom_id).toBe(InteractionComponent.PlaylistSelect);
        expect(select.options.find((o) => o.value === MapsPlaylistType.HCS_CURRENT.toString())?.default).toBe(true);
        expect(select.options.find((o) => o.value === MapsPlaylistType.HCS_HISTORICAL.toString())?.default).toBe(false);
      });
    });

    describe("format select", () => {
      it("returns deferred response and jobToComplete", () => {
        const interaction = aFakeFormatSelectInteraction(MapsFormatType.RANDOM, 3, MapsPlaylistType.HCS_CURRENT);

        const { response, jobToComplete } = command.execute(interaction);

        expect(response).toEqual<APIInteractionResponse>({
          type: InteractionResponseType.DeferredMessageUpdate,
        });
        expect(jobToComplete).toBeInstanceOf(Function);
      });

      it("calls updateDeferredReply when format is switched to RANDOM", async () => {
        const interaction = aFakeFormatSelectInteraction(
          MapsFormatType.RANDOM,
          5,
          MapsPlaylistType.HCS_CURRENT,
          MapsFormatType.RANDOM,
        );
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(typeof embed?.title).toBe("string");
        expect(embed?.title ?? "").toContain(MapsPlaylistType.HCS_CURRENT);

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("5");

        // Verify format select has RANDOM selected
        const formatSelect = data.components?.find(
          (c) =>
            c.type === ComponentType.ActionRow &&
            c.components.some(
              (comp) =>
                comp.type === ComponentType.StringSelect &&
                comp.custom_id === InteractionComponent.FormatSelect.toString(),
            ),
        );
        expect(formatSelect).toBeDefined();
      });

      it("calls updateDeferredReply when format is switched to OBJECTIVE", async () => {
        const interaction = aFakeFormatSelectInteraction(
          MapsFormatType.OBJECTIVE,
          3,
          MapsPlaylistType.HCS_HISTORICAL,
          MapsFormatType.OBJECTIVE,
        );
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toBeDefined();
        expect(embed?.title).toContain(MapsPlaylistType.HCS_HISTORICAL);

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("3");
      });

      it("calls updateDeferredReply when format is switched to SLAYER", async () => {
        const interaction = aFakeFormatSelectInteraction(
          MapsFormatType.SLAYER,
          7,
          MapsPlaylistType.HCS_CURRENT,
          MapsFormatType.SLAYER,
        );
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        const [, data] = updateDeferredReplySpy.mock.calls[0] as [string, APIInteractionResponseCallbackData];
        const embed = data.embeds?.[0];

        expect(embed).toBeDefined();
        expect(embed?.title).toBeDefined();

        expect(
          getSelectMenu(data.components, InteractionComponent.CountSelect).options.find(
            (option) => option.default === true,
          )?.value,
        ).toBe("7");
      });
    });
  });

  describe("getMapModesForPlaylist integration", () => {
    it("calls getMapModesForPlaylist and passes availableModes to MapsEmbed", async () => {
      const interaction = aFakeMapsInteractionWith();
      const { jobToComplete } = command.execute(interaction);

      const getMapModesForPlaylistSpy = vi.spyOn(services.haloService, "getMapModesForPlaylist");

      await jobToComplete?.();

      expect(getMapModesForPlaylistSpy).toHaveBeenCalledOnce();
      expect(getMapModesForPlaylistSpy).toHaveBeenCalledWith(MapsPlaylistType.HCS_CURRENT);
    });

    it("calls getMapModesForPlaylist with correct playlist when switching playlists", async () => {
      const interaction = aFakePlaylistSelectInteraction(
        MapsPlaylistType.HCS_HISTORICAL,
        5,
        MapsPlaylistType.HCS_HISTORICAL,
      );
      const { jobToComplete } = command.execute(interaction);

      const getMapModesForPlaylistSpy = vi.spyOn(services.haloService, "getMapModesForPlaylist");

      await jobToComplete?.();

      expect(getMapModesForPlaylistSpy).toHaveBeenCalledOnce();
      expect(getMapModesForPlaylistSpy).toHaveBeenCalledWith(MapsPlaylistType.HCS_HISTORICAL);
    });
  });

  describe("error handling in jobToComplete", () => {
    let logErrorSpy: MockInstance;
    let updateDeferredReplyWithErrorSpy: MockInstance;

    beforeEach(() => {
      logErrorSpy = vi.spyOn(services.logService, "error");
      updateDeferredReplyWithErrorSpy = vi
        .spyOn(services.discordService, "updateDeferredReplyWithError")
        .mockResolvedValue(apiMessage);
    });

    describe("application command errors", () => {
      it("logs error and calls updateDeferredReplyWithError when generateMaps fails", async () => {
        const testError = new Error("Failed to generate maps");
        vi.spyOn(services.haloService, "generateMaps").mockRejectedValue(testError);

        const interaction = aFakeMapsInteractionWith();
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
        expect(updateDeferredReplySpy).not.toHaveBeenCalled();
      });

      it("logs error and calls updateDeferredReplyWithError when getMapModesForPlaylist fails", async () => {
        const testError = new Error("Failed to fetch map modes");
        vi.spyOn(services.haloService, "getMapModesForPlaylist").mockRejectedValue(testError);

        const interaction = aFakeMapsInteractionWith();
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
        expect(updateDeferredReplySpy).not.toHaveBeenCalled();
      });

      it("logs error and calls updateDeferredReplyWithError when updateDeferredReply fails", async () => {
        const testError = new Error("Failed to update reply");
        updateDeferredReplySpy.mockRejectedValue(testError);

        const interaction = aFakeMapsInteractionWith();
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
      });
    });

    describe("button interaction errors", () => {
      it("logs error and calls updateDeferredReplyWithError when roll button fails", async () => {
        const testError = new Error("Failed to regenerate maps");
        vi.spyOn(services.haloService, "generateMaps").mockRejectedValue(testError);

        const interaction = aFakeButtonInteraction(InteractionComponent.Regenerate);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
        expect(updateDeferredReplySpy).not.toHaveBeenCalled();
      });

      it("logs error and calls updateDeferredReplyWithError when initiate button createMessage fails", async () => {
        const testError = new Error("Failed to create message");
        vi.spyOn(services.discordService, "createMessage").mockRejectedValue(testError);

        const interaction = aFakeButtonInteraction(InteractionComponent.Initiate);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
      });
    });

    describe("playlist select errors", () => {
      it("logs error and calls updateDeferredReplyWithError when playlist change fails", async () => {
        const testError = new Error("Failed to change playlist");
        vi.spyOn(services.haloService, "generateMaps").mockRejectedValue(testError);

        const interaction = aFakePlaylistSelectInteraction(MapsPlaylistType.HCS_HISTORICAL);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
        expect(updateDeferredReplySpy).not.toHaveBeenCalled();
      });
    });

    describe("format select errors", () => {
      it("logs error and calls updateDeferredReplyWithError when format change fails", async () => {
        const testError = new Error("Failed to change format");
        vi.spyOn(services.haloService, "generateMaps").mockRejectedValue(testError);

        const interaction = aFakeFormatSelectInteraction(MapsFormatType.RANDOM);
        const { jobToComplete } = command.execute(interaction);

        await jobToComplete?.();

        expect(logErrorSpy).toHaveBeenCalledWith(testError);
        expect(updateDeferredReplyWithErrorSpy).toHaveBeenCalledWith("fake-token", testError);
        expect(updateDeferredReplySpy).not.toHaveBeenCalled();
      });
    });
  });
});
