import type {
  APIEmbed,
  APIInteractionResponseCallbackData,
  APIMessageTopLevelComponent,
  APISelectMenuOption,
} from "discord-api-types/v10";
import { ComponentType, ButtonStyle } from "discord-api-types/v10";
import { HCS_LAST_UPDATED, MAP_COUNTS } from "../services/halo/hcs";
import type { MapMode } from "../services/halo/hcs";
import type { DiscordService } from "../services/discord/discord";
import { GAMECOACH_GG_URLS } from "../commands/maps/gamecoachgg";
import { MapsFormatType, MapsPlaylistType } from "../services/database/types/guild_config";
import { BaseTableEmbed } from "./base-table-embed";
import { EmbedColors } from "./colors";

export enum InteractionComponent {
  Initiate = "btn_maps_initiate",
  CountSelect = "select_maps_count",
  Regenerate = "btn_maps_regenerate",
  Confirm = "btn_maps_confirm",
  Clear = "btn_maps_clear",
  ConfirmClear = "btn_maps_confirm_clear",
  CancelClear = "btn_maps_cancel_clear",
  PlaylistSelect = "select_maps_playlist",
  FormatSelect = "select_maps_format",
  Repost = "btn_maps_repost",
}

const DISCORD_EMBED_FIELD_VALUE_LIMIT = 1024;

function exceedsDiscordFieldLimit(row: string[], columnLengths: number[], hasPreviousRows: boolean): boolean {
  for (let column = 0; column < row.length; column++) {
    const nextLength = (columnLengths[column] ?? 0) + (hasPreviousRows ? 1 : 0) + (row[column]?.length ?? 0);
    if (nextLength > DISCORD_EMBED_FIELD_VALUE_LIMIT) {
      return true;
    }
  }
  return false;
}

export const mapPlaylistLabels: Record<MapsPlaylistType, string> = {
  [MapsPlaylistType.HCS_CURRENT]: "LVT Pro League - Current",
  [MapsPlaylistType.HCS_HISTORICAL]: "HCS + LVT Pro League - Historical",
  [MapsPlaylistType.RANKED_ARENA]: "Ranked Arena",
  [MapsPlaylistType.RANKED_SLAYER]: "Ranked Slayer",
  [MapsPlaylistType.RANKED_SNIPERS]: "Ranked Snipers",
  [MapsPlaylistType.RANKED_TACTICAL]: "Ranked Tactical",
  [MapsPlaylistType.RANKED_DOUBLES]: "Ranked Doubles",
  [MapsPlaylistType.RANKED_FFA]: "Ranked FFA",
  [MapsPlaylistType.RANKED_SQUAD_BATTLE]: "Ranked Squad Battle",
};

export const mapPlaylistDescriptions: Record<MapsPlaylistType, string> = {
  [MapsPlaylistType.HCS_CURRENT]: `The current maps and modes of the LVT Pro League (as of ${HCS_LAST_UPDATED})`,
  [MapsPlaylistType.HCS_HISTORICAL]: "All maps and modes that have been played at any HCS + LVT Pro League event",
  [MapsPlaylistType.RANKED_ARENA]: "Ranked Arena playlist",
  [MapsPlaylistType.RANKED_SLAYER]: "Ranked Slayer playlist",
  [MapsPlaylistType.RANKED_SNIPERS]: "Ranked Snipers playlist",
  [MapsPlaylistType.RANKED_TACTICAL]: "Ranked Tactical playlist",
  [MapsPlaylistType.RANKED_DOUBLES]: "Ranked Doubles playlist",
  [MapsPlaylistType.RANKED_FFA]: "Ranked FFA playlist",
  [MapsPlaylistType.RANKED_SQUAD_BATTLE]: "Ranked Squad Battle playlist",
};

export const mapFormatLabels: Record<MapsFormatType, string> = {
  [MapsFormatType.HCS]: "HCS",
  [MapsFormatType.RANDOM]: "Random",
  [MapsFormatType.OBJECTIVE]: "Objective only",
  [MapsFormatType.SLAYER]: "Slayer only",
};

export const mapFormatDescriptions: Record<MapsFormatType, string> = {
  [MapsFormatType.HCS]: "Obj, slayer, obj, obj, slayer, ...",
  [MapsFormatType.RANDOM]: "Randomly pick objective or slayer for each map",
  [MapsFormatType.OBJECTIVE]: "Only pick objective modes",
  [MapsFormatType.SLAYER]: "Only pick slayer modes",
};

interface MapsEmbedData {
  userId: string;
  locked?: boolean | undefined;
  clearConfirmation?: boolean | undefined;
  clearConfirmationUserId?: string | undefined;
  playlist: MapsPlaylistType;
  format: MapsFormatType;
  count: number;
  maps: {
    mode: MapMode;
    map: string;
  }[];
  availableModes: MapMode[];
}

interface MapsEmbedServices {
  discordService: DiscordService;
}

export class MapsEmbed extends BaseTableEmbed {
  private readonly services: MapsEmbedServices;
  private readonly data: MapsEmbedData;

  constructor(services: MapsEmbedServices, data: MapsEmbedData) {
    super();
    this.services = services;
    this.data = data;
  }

  get embed(): APIEmbed {
    const { playlist, format, maps, userId } = this.data;
    const { discordService } = this.services;

    const userDisplay = `<@${userId}>`;

    const embed: APIEmbed = {
      title: `Maps: ${mapPlaylistLabels[playlist]}`,
      color: EmbedColors.NEUTRAL,
      ...(maps.length === 0 ? { description: "No maps selected" } : {}),
    };

    const titles = ["#", "Mode", "Map"];
    const rows = maps.map(({ mode, map }, index) => {
      const gamecoachGgUrl = GAMECOACH_GG_URLS[map];
      const mapDisplay =
        gamecoachGgUrl != null ? `[${map} ${discordService.getEmojiFromName("GameCoachGG")}](${gamecoachGgUrl})` : map;
      return [String(index + 1), mode, mapDisplay];
    });

    this.addMapFields(embed, titles, rows);

    const attributionLabel = this.data.locked === true ? "Confirmed by" : "Generated by";
    embed.fields ??= [];
    embed.fields.push({
      name: "",
      value: `-# ${attributionLabel} ${userDisplay} | Format: ${mapFormatLabels[format]}`,
    });

    return embed;
  }

  get actions(): APIMessageTopLevelComponent[] {
    const { count, playlist, format, locked = false, clearConfirmation = false } = this.data;

    const selectionRows: APIMessageTopLevelComponent[] = [
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.CountSelect,
            options: this.getCountOptions(count),
            placeholder: "Select number of maps",
            ...(clearConfirmation ? { disabled: true } : {}),
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.PlaylistSelect,
            options: this.getPlaylistOptions(playlist),
            placeholder: "Select a playlist",
            ...(clearConfirmation ? { disabled: true } : {}),
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.FormatSelect,
            options: this.getFormats(format),
            ...(clearConfirmation ? { disabled: true } : {}),
          },
        ],
      },
    ];

    if (clearConfirmation) {
      return [
        ...(locked ? [] : selectionRows),
        {
          type: ComponentType.ActionRow,
          components: [
            {
              type: ComponentType.Button,
              custom_id: InteractionComponent.ConfirmClear,
              label: "Confirm clear",
              style: ButtonStyle.Danger,
              emoji: { name: "🗑️" },
            },
            {
              type: ComponentType.Button,
              custom_id: InteractionComponent.CancelClear,
              label: "Cancel",
              style: ButtonStyle.Secondary,
              emoji: { name: "❌" },
            },
          ],
        },
      ];
    }

    if (locked) {
      return [
        {
          type: ComponentType.ActionRow,
          components: [
            {
              type: ComponentType.Button,
              custom_id: InteractionComponent.Clear,
              label: "Clear maps",
              style: ButtonStyle.Danger,
              emoji: { name: "🗑️" },
            },
            {
              type: ComponentType.Button,
              custom_id: InteractionComponent.Repost,
              label: "Move to bottom of chat",
              style: ButtonStyle.Secondary,
              emoji: { name: "⏬" },
            },
          ],
        },
      ];
    }

    return [
      ...selectionRows,
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Regenerate,
            label: "Regenerate",
            style: ButtonStyle.Primary,
            emoji: { name: "🔄" },
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Confirm,
            label: "Confirm maps",
            style: ButtonStyle.Success,
            disabled: this.data.maps.length === 0,
            emoji: { name: "✅" },
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Clear,
            label: "Clear maps",
            style: ButtonStyle.Danger,
            emoji: { name: "🗑️" },
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Repost,
            label: "Move to bottom of chat",
            style: ButtonStyle.Secondary,
            emoji: {
              name: "⏬",
            },
          },
        ],
      },
    ];
  }

  toMessageData(): APIInteractionResponseCallbackData {
    return {
      embeds: [this.embed, ...(this.data.clearConfirmation === true ? [this.clearConfirmationEmbed] : [])],
      components: this.actions,
    };
  }

  get clearConfirmationEmbed(): APIEmbed {
    return {
      title: "Clear planned maps?",
      description: "Confirm that the planned maps should be removed from this queue.",
      color: EmbedColors.NEUTRAL,
      fields: [
        {
          name: "",
          value: `-# Clear initiated by <@${this.data.clearConfirmationUserId ?? this.data.userId}>`,
        },
      ],
    };
  }

  private getPlaylistOptions(playlist: MapsPlaylistType): APISelectMenuOption[] {
    return Object.entries(mapPlaylistLabels).map(([value, label]) => ({
      label,
      value,
      description: mapPlaylistDescriptions[value as MapsPlaylistType],
      default: (value as MapsPlaylistType) === playlist,
    }));
  }

  private addMapFields(embed: APIEmbed, titles: string[], rows: string[][]): void {
    let chunk: string[][] = [];
    let columnLengths = titles.map(() => 0);

    for (const row of rows) {
      if (exceedsDiscordFieldLimit(row, columnLengths, chunk.length > 0) && chunk.length > 0) {
        this.addEmbedFields(embed, titles, [titles, ...chunk]);
        chunk = [];
        columnLengths = titles.map(() => 0);
      }

      chunk.push(row);
      for (let column = 0; column < row.length; column++) {
        columnLengths[column] = (columnLengths[column] ?? 0) + (chunk.length > 1 ? 1 : 0) + (row[column]?.length ?? 0);
      }
    }

    if (chunk.length > 0) {
      this.addEmbedFields(embed, titles, [titles, ...chunk]);
    }
  }

  private getCountOptions(count: number): APISelectMenuOption[] {
    return MAP_COUNTS.map((value) => ({
      label: value.toString(),
      value: value.toString(),
      default: value === count,
    }));
  }

  private getFormats(format: MapsFormatType): APISelectMenuOption[] {
    const hasObjective = this.data.availableModes.length > 1;
    if (hasObjective) {
      return [
        {
          label: mapFormatLabels[MapsFormatType.HCS],
          value: MapsFormatType.HCS,
          description: mapFormatDescriptions[MapsFormatType.HCS],
          default: format === MapsFormatType.HCS,
        },
        {
          label: mapFormatLabels[MapsFormatType.RANDOM],
          value: MapsFormatType.RANDOM,
          description: mapFormatDescriptions[MapsFormatType.RANDOM],
          default: format === MapsFormatType.RANDOM,
        },
        {
          label: mapFormatLabels[MapsFormatType.OBJECTIVE],
          value: MapsFormatType.OBJECTIVE,
          description: mapFormatDescriptions[MapsFormatType.OBJECTIVE],
          default: format === MapsFormatType.OBJECTIVE,
        },
        {
          label: mapFormatLabels[MapsFormatType.SLAYER],
          value: MapsFormatType.SLAYER,
          description: mapFormatDescriptions[MapsFormatType.SLAYER],
          default: format === MapsFormatType.SLAYER,
        },
      ];
    }

    return [
      {
        label: mapFormatLabels[MapsFormatType.SLAYER],
        value: MapsFormatType.SLAYER,
        description: mapFormatDescriptions[MapsFormatType.SLAYER],
        default: true,
      },
    ];
  }
}
