import type {
  APIEmbed,
  APIInteractionResponseCallbackData,
  APIMessageTopLevelComponent,
  APISelectMenuOption,
} from "discord-api-types/v10";
import { ComponentType, ButtonStyle } from "discord-api-types/v10";
import { HCS_LAST_UPDATED, type MapMode } from "../services/halo/hcs.mjs";
import type { DiscordService } from "../services/discord/discord.mjs";
import { GAMECOACH_GG_URLS } from "../commands/maps/gamecoachgg.mjs";
import { MapsFormatType, MapsPlaylistType } from "../services/database/types/guild_config.mjs";
import { BaseTableEmbed } from "./base-table-embed.mjs";

export enum InteractionComponent {
  Initiate = "btn_maps_initiate",
  Roll1 = "btn_maps_roll_1",
  Roll3 = "btn_maps_roll_3",
  Roll5 = "btn_maps_roll_5",
  Roll7 = "btn_maps_roll_7",
  PlaylistSelect = "select_maps_playlist",
  FormatSelect = "select_maps_format",
  Repost = "btn_maps_repost",
}

export const mapPlaylistLabels: Record<MapsPlaylistType, string> = {
  [MapsPlaylistType.HCS_CURRENT]: "HCS - Current",
  [MapsPlaylistType.HCS_HISTORICAL]: "HCS - Historical",
  [MapsPlaylistType.RANKED_ARENA]: "Ranked Arena",
  [MapsPlaylistType.RANKED_SLAYER]: "Ranked Slayer",
  [MapsPlaylistType.RANKED_SNIPERS]: "Ranked Snipers",
  [MapsPlaylistType.RANKED_TACTICAL]: "Ranked Tactical",
  [MapsPlaylistType.RANKED_DOUBLES]: "Ranked Doubles",
  [MapsPlaylistType.RANKED_FFA]: "Ranked FFA",
  [MapsPlaylistType.RANKED_SQUAD_BATTLE]: "Ranked Squad Battle",
};

export const mapPlaylistDescriptions: Record<MapsPlaylistType, string> = {
  [MapsPlaylistType.HCS_CURRENT]: `The current maps and modes of HCS (as of ${HCS_LAST_UPDATED})`,
  [MapsPlaylistType.HCS_HISTORICAL]: "All maps and modes that have been played at any HCS major event",
  [MapsPlaylistType.RANKED_ARENA]: "Ranked Arena playlist",
  [MapsPlaylistType.RANKED_SLAYER]: "Ranked Slayer playlist",
  [MapsPlaylistType.RANKED_SNIPERS]: "Ranked Snipers playlist",
  [MapsPlaylistType.RANKED_TACTICAL]: "Ranked Tactical playlist",
  [MapsPlaylistType.RANKED_DOUBLES]: "Ranked Doubles playlist",
  [MapsPlaylistType.RANKED_FFA]: "Ranked FFA playlist",
  [MapsPlaylistType.RANKED_SQUAD_BATTLE]: "Ranked Squad Battle playlist",
};

export const mapFormatLabels: Record<MapsFormatType, string> = {
  [MapsFormatType.HCS]: "HCS",
  [MapsFormatType.RANDOM]: "Random",
  [MapsFormatType.OBJECTIVE]: "Objective only",
  [MapsFormatType.SLAYER]: "Slayer only",
};

export const mapFormatDescriptions: Record<MapsFormatType, string> = {
  [MapsFormatType.HCS]: "Obj, slayer, obj, obj, slayer, ...",
  [MapsFormatType.RANDOM]: "Randomly pick objective or slayer for each map",
  [MapsFormatType.OBJECTIVE]: "Only pick objective modes",
  [MapsFormatType.SLAYER]: "Only pick slayer modes",
};

interface MapsEmbedData {
  userId: string;
  playlist: MapsPlaylistType;
  format: MapsFormatType;
  count: number;
  maps: {
    mode: MapMode;
    map: string;
  }[];
  availableModes: MapMode[];
}

interface MapsEmbedServices {
  discordService: DiscordService;
}

export class MapsEmbed extends BaseTableEmbed {
  private readonly services: MapsEmbedServices;
  private readonly data: MapsEmbedData;

  constructor(services: MapsEmbedServices, data: MapsEmbedData) {
    super();
    this.services = services;
    this.data = data;
  }

  get embed(): APIEmbed {
    const { playlist, maps, userId } = this.data;
    const { discordService } = this.services;

    const userDisplay = `<@${userId}>`;

    const embed: APIEmbed = {
      title: `Maps: ${mapPlaylistLabels[playlist]}`,
      color: 0x5865f2,
    };

    const titles = ["#", "Mode", "Map"];
    const data = [
      titles, // Header row
      ...maps.map(({ mode, map }, index) => {
        const gamecoachGgUrl = GAMECOACH_GG_URLS[map];
        const mapDisplay =
          gamecoachGgUrl != null
            ? `[${map} ${discordService.getEmojiFromName("GameCoachGG")}](${gamecoachGgUrl})`
            : map;
        return [String(index + 1), mode, mapDisplay];
      }),
    ];

    this.addEmbedFields(embed, titles, data);

    // Add the "Generated by" field
    embed.fields ??= [];
    embed.fields.push({
      name: "",
      value: `-# Generated by ${userDisplay}`,
    });

    return embed;
  }

  get actions(): APIMessageTopLevelComponent[] {
    const { count, playlist, format } = this.data;

    return [
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll1,
            label: "Regen maps (count: 1)",
            style: count === 1 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll3,
            label: "Regen maps (count: 3)",
            style: count === 3 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll5,
            label: "Regen maps (count: 5)",
            style: count === 5 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Roll7,
            label: "Regen maps (count: 7)",
            style: count === 7 ? ButtonStyle.Primary : ButtonStyle.Secondary,
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.PlaylistSelect,
            options: this.getPlaylistOptions(playlist),
            placeholder: "Select a playlist",
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.StringSelect,
            custom_id: InteractionComponent.FormatSelect,
            options: this.getFormats(format),
          },
        ],
      },
      {
        type: ComponentType.ActionRow,
        components: [
          {
            type: ComponentType.Button,
            custom_id: InteractionComponent.Repost,
            label: "Move to bottom of chat",
            style: ButtonStyle.Secondary,
            emoji: {
              name: "⏬",
            },
          },
        ],
      },
    ];
  }

  toMessageData(): APIInteractionResponseCallbackData {
    return {
      embeds: [this.embed],
      components: this.actions,
    };
  }

  private getPlaylistOptions(playlist: MapsPlaylistType): APISelectMenuOption[] {
    return Object.entries(mapPlaylistLabels).map(([value, label]) => ({
      label,
      value,
      description: mapPlaylistDescriptions[value as MapsPlaylistType],
      default: (value as MapsPlaylistType) === playlist,
    }));
  }

  private getFormats(format: MapsFormatType): APISelectMenuOption[] {
    const hasObjective = this.data.availableModes.length > 1;
    if (hasObjective) {
      return [
        {
          label: mapFormatLabels[MapsFormatType.HCS],
          value: MapsFormatType.HCS,
          description: mapFormatDescriptions[MapsFormatType.HCS],
          default: format === MapsFormatType.HCS,
        },
        {
          label: mapFormatLabels[MapsFormatType.RANDOM],
          value: MapsFormatType.RANDOM,
          description: mapFormatDescriptions[MapsFormatType.RANDOM],
          default: format === MapsFormatType.RANDOM,
        },
        {
          label: mapFormatLabels[MapsFormatType.OBJECTIVE],
          value: MapsFormatType.OBJECTIVE,
          description: mapFormatDescriptions[MapsFormatType.OBJECTIVE],
          default: format === MapsFormatType.OBJECTIVE,
        },
        {
          label: mapFormatLabels[MapsFormatType.SLAYER],
          value: MapsFormatType.SLAYER,
          description: mapFormatDescriptions[MapsFormatType.SLAYER],
          default: format === MapsFormatType.SLAYER,
        },
      ];
    }

    return [
      {
        label: mapFormatLabels[MapsFormatType.SLAYER],
        value: MapsFormatType.SLAYER,
        description: mapFormatDescriptions[MapsFormatType.SLAYER],
        default: true,
      },
    ];
  }
}
