import type { MockInstance } from "vitest";
import { describe, it, expect, vi, beforeEach } from "vitest";
import { ComponentType } from "discord-api-types/v10";
import { Preconditions } from "@guilty-spark/shared/base/preconditions";
import { MapsEmbed, InteractionComponent } from "../maps-embed";
import type { DiscordService } from "../../services/discord/discord";
import { aFakeDiscordServiceWith } from "../../services/discord/fakes/discord.fake";
import { MapsPlaylistType, MapsFormatType } from "../../services/database/types/guild_config";
import { MAP_COUNTS } from "../../services/halo/hcs";

describe("MapsEmbed", () => {
  let discordService: DiscordService;
  let getEmojiFromNameSpy: MockInstance<typeof discordService.getEmojiFromName>;
  const testUserId = "user123";

  const mockMaps = [
    { mode: "Slayer" as const, map: "Aquarius" },
    { mode: "Capture the Flag" as const, map: "Fortress" },
    { mode: "Strongholds" as const, map: "Live Fire" },
  ];

  const mockAvailableModes = ["Slayer" as const, "Capture the Flag" as const, "Strongholds" as const];

  beforeEach(() => {
    discordService = aFakeDiscordServiceWith();
    getEmojiFromNameSpy = vi.spyOn(discordService, "getEmojiFromName").mockReturnValue("🎮");
  });

  it("creates embed with correct title and maps data", () => {
    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 3,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.HCS,
        maps: mockMaps,
        availableModes: mockAvailableModes,
      },
    );

    const { embed } = mapsEmbed;

    expect(embed.title).toBe("Maps: LVT Pro League - Current");
    expect(embed.color).toBe(0x5865f2);
    expect(embed.fields).toHaveLength(4); // 3 columns + 1 generated by field

    // Check the fields structure
    expect(embed.fields?.[0]).toEqual({
      name: "#",
      value: "1\n2\n3",
      inline: true,
    });
    expect(embed.fields?.[1]).toEqual({
      name: "Mode",
      value: "Slayer\nCapture the Flag\nStrongholds",
      inline: true,
    });
    expect(embed.fields?.[2]).toEqual({
      name: "Map",
      value:
        "[Aquarius 🎮](https://gamecoach.gg/esports/haloinfinite/aquarius)\n[Fortress 🎮](https://gamecoach.gg/esports/haloinfinite/fortress)\n[Live Fire 🎮](https://gamecoach.gg/esports/haloinfinite/livefire)",
      inline: true,
    });
    expect(embed.fields?.[3]).toEqual({
      name: "",
      value: "-# Generated by <@user123>",
    });
  });

  it("creates action components", () => {
    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 5,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.RANDOM,
        maps: mockMaps,
        availableModes: mockAvailableModes,
      },
    );

    const { actions } = mapsEmbed;

    expect(actions).toHaveLength(4); // 4 action rows
    expect(actions[0]?.type).toBe(ComponentType.ActionRow);
    if (actions[0]?.type === ComponentType.ActionRow) {
      const countSelect = Preconditions.checkExists(actions[0].components[0]);
      if (countSelect.type === ComponentType.StringSelect) {
        expect(countSelect.custom_id).toBe(InteractionComponent.CountSelect);
        expect(countSelect.options.map((option) => Number(option.value))).toEqual(MAP_COUNTS);
        expect(countSelect.options.find((option) => option.default === true)?.value).toBe("5");
      }
    }
    const [, , , finalActionRow] = actions;
    expect(finalActionRow?.type).toBe(ComponentType.ActionRow);
    if (finalActionRow?.type === ComponentType.ActionRow) {
      expect(
        finalActionRow.components.map((component) => ("custom_id" in component ? component.custom_id : "")),
      ).toEqual([
        InteractionComponent.Regenerate,
        InteractionComponent.Confirm,
        InteractionComponent.Clear,
        InteractionComponent.Repost,
      ]);
      expect(finalActionRow.components[0]).toMatchObject({ emoji: { name: "🔄" } });
      expect(finalActionRow.components[1]).toMatchObject({ emoji: { name: "✅" } });
      expect(finalActionRow.components[2]).toMatchObject({ emoji: { name: "🗑️" } });
    }
  });

  it("returns complete message data", () => {
    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 3,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.HCS,
        maps: mockMaps,
        availableModes: mockAvailableModes,
      },
    );

    const messageData = mapsEmbed.toMessageData();

    expect(messageData.embeds?.length).toBe(1);
    expect(messageData.components?.length).toBe(4);
    expect(messageData.embeds?.[0]).toStrictEqual(mapsEmbed.embed);
    expect(messageData.components).toStrictEqual(mapsEmbed.actions);
  });

  it("handles maps with GameCoach.gg URLs", () => {
    const mapsWithUrl = [
      { mode: "Slayer" as const, map: "Aquarius" }, // Has GameCoach.gg URL
    ];

    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 1,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.HCS,
        maps: mapsWithUrl,
        availableModes: ["Slayer"],
      },
    );

    const { embed } = mapsEmbed;
    const mapField = embed.fields?.[2]; // Map column

    // Should include the GameCoach.gg link
    expect(mapField?.value).toContain("[Aquarius 🎮]");
    expect(getEmojiFromNameSpy).toHaveBeenCalledWith("GameCoachGG");
  });

  it("splits 13-map lists so every embed field stays within Discord's limit", () => {
    getEmojiFromNameSpy.mockReturnValue("<:GameCoachGG:1410461403663568926>");
    const maps = Array.from({ length: 13 }, () => ({ mode: "Slayer" as const, map: "Live Fire" }));
    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 13,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.HCS,
        maps,
        availableModes: mockAvailableModes,
      },
    );

    const fields = mapsEmbed.embed.fields ?? [];
    const mapFields = fields.filter((field) => field.name === "Map");

    expect(fields.every((field) => field.value.length <= 1024)).toBe(true);
    expect(mapFields.flatMap((field) => field.value.split("\n"))).toHaveLength(13);
    expect(mapFields).toHaveLength(2);
  });

  it("shows only slayer format option when playlist has no objective modes", () => {
    const slayerOnlyMaps = [{ mode: "Slayer" as const, map: "Aquarius" }];

    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 1,
        playlist: MapsPlaylistType.RANKED_SLAYER,
        format: MapsFormatType.SLAYER,
        maps: slayerOnlyMaps,
        availableModes: ["Slayer"],
      },
    );

    const { actions } = mapsEmbed;
    // Should have 4 action rows
    expect(actions).toHaveLength(4);
  });

  it("shows all format options when playlist has objective modes", () => {
    const mapsEmbed = new MapsEmbed(
      { discordService },
      {
        userId: testUserId,
        count: 3,
        playlist: MapsPlaylistType.HCS_CURRENT,
        format: MapsFormatType.HCS,
        maps: mockMaps,
        availableModes: mockAvailableModes,
      },
    );

    const { actions } = mapsEmbed;
    // Should have 4 action rows
    expect(actions).toHaveLength(4);
  });
});
