name: Deploy

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug the event payload"
        required: false
        type: boolean
  workflow_run:
    workflows: [Typecheck]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'staging' }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 10
    steps:
      - name: Debug
        if: ${{ github.event.inputs.debug == true }}
        run: ${{ tojson(github.event) }}
        shell: cat {0}

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build & Deploy Worker
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: ${{ github.event.workflow_run.head_branch == 'main' && 'production' || 'staging' }}
          postCommands: echo "WRANGLER_OUTPUT_DIR=$WRANGLER_OUTPUT_FILE_DIRECTORY" >> $GITHUB_ENV
          vars: |
            DISCORD_APP_ID
            DISCORD_PUBLIC_KEY
            XBOX_USERNAME
            PROXY_WORKER_URL
          secrets: |
            DISCORD_TOKEN
            XBOX_PASSWORD
            PROXY_WORKER_TOKEN
        env:
          DISCORD_APP_ID: ${{ vars.DISCORD_APP_ID }}
          DISCORD_PUBLIC_KEY: ${{ vars.DISCORD_PUBLIC_KEY }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          XBOX_USERNAME: ${{ vars.XBOX_USERNAME }}
          XBOX_PASSWORD: ${{ secrets.XBOX_PASSWORD }}
          PROXY_WORKER_URL: ${{ vars.PROXY_WORKER_URL }}
          PROXY_WORKER_TOKEN: ${{ secrets.PROXY_WORKER_TOKEN }}

      - name: Upload Source Maps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          if [ -n "$WRANGLER_OUTPUT_DIR" ] && [ -d "$WRANGLER_OUTPUT_DIR" ]; then
            echo "📁 Found Wrangler output directory: $WRANGLER_OUTPUT_DIR"
            if ls "$WRANGLER_OUTPUT_DIR"/*.js.map 1> /dev/null 2>&1; then
              echo "🗺️ Found source maps, uploading to Sentry..."
              npx sentry-cli sourcemaps inject --org david-houweling --project guilty-spark "$WRANGLER_OUTPUT_DIR"
              npx sentry-cli sourcemaps upload --org david-houweling --project guilty-spark "$WRANGLER_OUTPUT_DIR"
              echo "✅ Source maps uploaded successfully!"
            else
              echo "⚠️ No source map files found in $WRANGLER_OUTPUT_DIR"
            fi
          else
            echo "❌ Wrangler output directory not found or empty"
            exit 1
          fi

  deploy-cancel:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1
